version: '3.5'
services:
  web:
    build: '.'
    ports:
     - "60002:80"
    external_links:
      - sentry-server:sentry
    environment: 
      # ASSETDB_DEBUG: 1
      SENTRY_DSN: ${SENTRY_DSN}
    volumes:
      - /srv/assetdb:/srv/assetdb