version: '3.5'
services:
  web:
    build: '.'
    ports:
     - "60002:80"
    volumes:
      - '/srv/assetdb:/srv/assetdb'
    external_links:
      - sentry-server:sentry
    environment: 
      # CSHEET_DEBUG: 1
      SENTRY_DSN: ${SENTRY_DSN}
    